# Generated by Django 5.0.7 on 2024-08-07 19:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ott_name', models.CharField(max_length=250)),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='ott',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='ott', to='ott.movieplatform'),
            preserve_default=False,
        ),
    ]
